### PR TITLE
Added contributors information

### LINKED ISSUE #6: Add contributors section to README
Would it be helpful to have a contributors section in the README? You could use [all-contributors](https://github.com/kentcdodds/all-contributors). I'm glad to submit a PR if you think it's a good idea.

### PR DESCRIPTION
**Pull request by raygesualdo**
Closes #6.

### CODE REVIEW

**Comment by zackify** [comment]
Do you think we need the review required turned on?

**Comment by raygesualdo** [comment]
Not necessarily. Does help keep eyes on all the changes though.

**Comment by zackify** [comment]
Also, do we want to always squash? or just merge all commits

**Comment by raygesualdo** [comment]
That is beyond my git expertise. What's the difference?

**Comment by zackify** [comment]
Turns the pull request into one single commit.

**Comment by zackify** [comment]
I did it for this one: https://github.com/Legitcode/legible/commit/4d8ec24c3771a588c92fdcc8a2c94ad9b3fc33b6

**Pull request merged**
